services:
  kafka-ui:
    extends:
      file: ./src/back-end/event-pipeline/viewer-compose.yaml
      service: kafka-ui
    networks:
      - site1
      - site2
      - site3
    environment:
      KAFKA_CLUSTERS_0_NAME: ${EVENT_HOST_SITE_1}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${EVENT_HOST_SITE_1}:${EVENT_PORT_SITE_1}
      KAFKA_CLUSTERS_1_NAME: ${EVENT_HOST_SITE_2}
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: ${EVENT_HOST_SITE_2}:${EVENT_PORT_SITE_2}
      KAFKA_CLUSTERS_2_NAME: ${EVENT_HOST_SITE_3}
      KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS: ${EVENT_HOST_SITE_3}:${EVENT_PORT_SITE_3}
  proxy-1:
    build:
      context: ./src/proxy/base-proxy
      dockerfile: Dockerfile
    volumes:
      - ./src/proxy/base-proxy:/app
      - ./utils/handlers:/app/src/handlers
      - ./site1/config.json:/app/src/config.json
      - ./site1/sharder/:/app/src/sharder/
    ports:
      - "${PROXY_1_EXTERNAL_PORT}:${PROXY_PORT}"
    # The watch command will check for changes in the code and restart the server
    command: sh -c "npm install && npm run watch"
    environment:
      PORT: ${PROXY_PORT} 
      EVENT_ADDRESS: ${EVENT_HOST_SITE_1}
      EVENT_PORT: ${EVENT_PORT_SITE_1}
      EVENT_CLIENT_ID: "proxy-1"
      REGION: "eu-be"
      MASTER: "${MASTER}"
      CONTROL_PORT: "${CONTROL_PORT}"
      IS_MASTER: "true"
    networks:
      - proxy
      - site1
  proxy-2:
    build:
      context: ./src/proxy/base-proxy
      dockerfile: Dockerfile
    volumes:
      - ./src/proxy/base-proxy:/app
      - ./utils/handlers:/app/src/handlers
    ports:
      - "${PROXY_2_EXTERNAL_PORT}:${PROXY_PORT}"
    # The watch command will check for changes in the code and restart the server
    command: sh -c "npm install && npm run watch"
    environment:
      PORT: ${PROXY_PORT} 
      EVENT_ADDRESS: ${EVENT_HOST_SITE_2}
      EVENT_PORT: ${EVENT_PORT_SITE_2}
      EVENT_CLIENT_ID: "proxy-2"
      REGION: "eu-spain"
      MASTER: "${MASTER}"
      CONTROL_PORT: "${CONTROL_PORT}"
    networks:
      - proxy
      - site2
  proxy-3:
    build:
      context: ./src/proxy/base-proxy
      dockerfile: Dockerfile
    volumes:
      - ./src/proxy/base-proxy:/app
      - ./utils/handlers:/app/src/handlers
    ports:
      - "${PROXY_3_EXTERNAL_PORT}:${PROXY_PORT}"
    # The watch command will check for changes in the code and restart the server
    command: sh -c "npm install && npm run watch"
    environment:
      PORT: ${PROXY_PORT} 
      EVENT_ADDRESS: ${EVENT_HOST_SITE_3}
      EVENT_PORT: ${EVENT_PORT_SITE_3}
      EVENT_CLIENT_ID: "proxy-3"
      REGION: "eu-uk"
      MASTER: "${MASTER}"
      CONTROL_PORT: "${CONTROL_PORT}"
    networks:
      - proxy
      - site3
  db-proxy-3-mapping:
    image: redis:alpine
    ports:
      - "${DB_MAPPING_EXTERNAL_PORT_3}:6379"
    volumes: 
      - ./src/back-end/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

networks:
  site1:
    name: site1
    external: true
  site2:
    name: site2
    external: true
  site3:
    name: site3
    external: true
  proxy:
    name: proxy
    external: true
