services:
  frontend:
    build: 
      context: ./src/front-end
      dockerfile: Dockerfile
    volumes:
      - ./src/front-end:/app
      - ./utils/types/product.ts:/app/src/types/product.ts
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      - PUBLIC_AUTH_SERVICE_URL=http://localhost:80
      - VITE_PRODUCT_URL=http://gateway:80
    command: npm run dev -- --host
    depends_on:
      - product

  product:
    build:
      context: ./src/back-end/product
      dockerfile: Dockerfile
    volumes:
      - ./src/back-end/product:/app
      - ./utils/types:/app/src/types
    ports:
      - "5000:5000"
    # The watch command will check for changes in the code and restart the server
    command: sh boot-in-order.sh 
    environment:
      - PORT=5000
      - DB_ADDRESS=event-store
      - DB_PORT=2113
    depends_on:
      event-store:
        condition: service_healthy

  event-store:
    extends:
      file: src/back-end/event_store_db/docker-compose.yaml
      service: event-store

  gateway:
    image: nginx:alpine
    volumes:
      - ./src/gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./src/gateway/template-variables:/etc/nginx/templates/10-variables.conf.template:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - product
    environment:
      - FRONTEND_URL=http://frontend:3000

networks:
  default:
    driver: bridge
