include:
  - src/back-end/event-pipeline/docker-compose.yaml # Event pipeline service (Kafka)
  - src/back-end/event-pipeline/viewer-compose.yaml # Event pipeline service (Kafka)
  - stock-compose.yaml # Stock services
  - order-compose.yaml
  - email-compose.yaml
  - users-compose.yaml

services:
  frontend:
    build: 
      context: ./src/front-end
      dockerfile: Dockerfile
    volumes:
      - ./src/front-end:/app
      - ./utils/types/product.ts:/app/src/types/product.ts
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      - PUBLIC_AUTH_SERVICE_URL=http://localhost:80
      # Because running on host machine 
      - VITE_GATEWAY_URL=http://localhost:80
    command: npm run dev -- --host
    depends_on:
      - stock 
  gateway:
    image: nginx:alpine
    volumes:
      - ./src/gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./src/gateway/template-variables:/etc/nginx/templates/10-variables.conf.template:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - stock
      - orders
    environment:
      - FRONTEND_URL=http://frontend:3000

networks:
  default:
    driver: bridge
