services:
  orders:
    build:
      context: ./src/back-end/orders
      dockerfile: Dockerfile
    volumes:
      - ./src/back-end/orders:/app
      - ./utils/types:/app/src/types
    ports:
      - "5050:5050"
    command: sh boot-in-order.sh
    depends_on:
      broker:
        condition: service_healthy

