services:
  orders:
    build:
      context: ./src/back-end/orders
      dockerfile: Dockerfile
    volumes:
      - ./src/back-end/orders:/app
      - ./utils/types:/app/src/types
      - ./utils/handlers:/app/src/handlers
      - ./utils/middleware/token.ts:/app/src/middleware/token.ts
    ports:
      - "5050:5050"
    environment:
      PORT: ${ORDER_PORT} 
    command: sh boot-in-order.sh
    depends_on:
      broker:
        condition: service_healthy

