services:
  proxy-1:
    build:
      context: ./src/proxy/base-proxy
      dockerfile: Dockerfile
    volumes:
      - ./src/proxy/base-proxy:/app
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
    # The watch command will check for changes in the code and restart the server
    command: sh -c "npm run watch"
    environment:
      PORT: ${PROXY_PORT} 
      EVENT_ADDRESS: ${EVENT_HOST}
      EVENT_PORT: ${EVENT_PORT}
    depends_on:
      broker:
        condition: service_healthy
