services:
  internal-gateway:
    image: nginx:alpine 
    volumes:
      - ./src/gateway/internal-nginx.conf:/etc/nginx/nginx.conf
      - ./src/gateway/template-variables:/etc/nginx/templates/10-variables.conf.template:ro
    depends_on:
      proxy-1:
        condition: service_healthy
  proxy-1:
    build:
      context: ./src/proxy/base-proxy
      dockerfile: Dockerfile
    volumes:
      - ./src/proxy/base-proxy:/app
      - ./utils/handlers:/app/src/handlers
    ports:
      - "${PROXY_EXTERNAL_PORT}:${PROXY_PORT}"
    # The watch command will check for changes in the code and restart the server
    command: sh -c "npm run watch"
    environment:
      PORT: ${PROXY_PORT} 
      EVENT_ADDRESS: ${EVENT_HOST}
      EVENT_PORT: ${EVENT_PORT}
      EVENT_CLIENT_ID: "proxy-1"
    depends_on:
      broker:
        condition: service_healthy
