services:
  broker:
    image: apache/kafka:latest
    # ports:
    #   - "9092:9092"
    #   - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:${EVENT_PORT},CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:${EVENT_PORT}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'metadata' | nc -z -w 2 localhost ${EVENT_PORT} > /dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 5
