include:
  # - ../src/back-end/event-pipeline/docker-compose.yaml # Event pipeline service (Kafka)
  - ../compose/products-compose-init.yaml # Product services
  - ../compose/stock-compose-init.yaml
  - ../compose/order-compose-init.yaml
  - ../compose/email-compose.yaml
  - ../compose/users-compose-init.yaml

services:
  frontend:
    build: 
      context: ../src/front-end
      dockerfile: Dockerfile
    volumes:
      - ../src/front-end/src:/app/src
      - ../utils/types/product.ts:/app/src/types/product.ts
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:${FRONTEND_PORT}"
    environment:
      - PUBLIC_AUTH_SERVICE_URL=http://localhost:80
      # Because running on host machine 
      - VITE_GATEWAY_URL=http://localhost:${GATEWAY_PORT}
    command: npm run dev -- --host
    depends_on:
      products:  
        condition: service_healthy
  gateway:
    build: 
      context: ../src/gateway
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ../src/gateway/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
      - proxy
    cap_add:
      - NET_ADMIN
    depends_on:
      - frontend


networks:
  default:
    name: site1
    driver: bridge
  proxy:
    name: proxy
    external: true
