services:
  orders:
    build:
      context: ../src/back-end/orders
      dockerfile: Dockerfile
    volumes:
      - ../src/back-end/orders:/app
      - ../utils/types:/app/src/types
      - ../utils/handlers:/app/src/handlers
      #- ../utils/middleware/token.ts:/app/src/middleware/token.ts
      - ../utils/middleware:/app/src/middleware # ONLY ONE TO NEED ALL FOLDER
    ports:
      - "${ORDERS_EXTERNAL_PORT}:${ORDERS_PORT}"
    environment:
      PORT: ${ORDERS_PORT} 
      DB_ADDRESS: ${DB_ORDERS_HOST}
      DB_PORT: ${DB_ORDERS_PORT}
      DB_KEYSPACE: ${DB_ORDERS_KEYSPACE} 
      EVENT_ADDRESS: ${EVENT_HOST} 
      EVENT_PORT: ${EVENT_PORT} 
      JWT_SECRET: ${JWT_SECRET}
    command: sh boot-in-order.sh
    depends_on:
      broker:
        condition: service_healthy
      db-orders:
        condition: service_healthy
  db-orders:
    image: redis:alpine
    ports:
      - "${DB_ORDERS_EXTERNAL_PORT}:${DB_ORDERS_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5 
